Fixed Compiling Example project
abbeycode/UnrarKit pull request #107
Opened 2022-08-01 14:18 UTC by gpotari

Fixes Building Example project. 
Added missing short version string key to info.plist. 

Also wanted to ask It is referencing a _large-archive.rar_ that is not present in the repo. I can see the reason why, just wanted to ask just in case...

2022-08-01 19:59 UTC, abbeycode requested changes
Thanks for pointing this out! I have a CI check that makes sure it always builds, but I don't run it often. I need to see if I can make a quick UI test that CI can run just to make sure it doesn't crash on startup.

I renamed this ticket and suggested an update to the CHANGELOG line (thanks for including that!) to reflect that it actually was compiling, it was just crashing on startup. Also would like to roll back the scheme upgrade check lines to keep the PR focused on what actually needed to change.

2022-08-01 19:59 UTC, abbeycode commented on CHANGELOG.md
> +* Fixed compile error for Example project. Added missing CFBundleShortVersionString key to Info.plist
Please update the CHANGELOG to reflect the actual nature of the problem being fixed (a crash, not a compilation error).

```suggestion
* Fix crash on start of Example app (PR #107 - Thanks to [@gpotari](https://github.com/gpotari))
```

2022-08-01 19:59 UTC, abbeycode commented on Example/UnrarExample.xcodeproj/xcshareddata/xcschemes/UnrarExample.xcscheme
> +   LastUpgradeVersion = "1400"
- [ ] Please revert

2022-08-01 19:59 UTC, abbeycode commented on UnrarKit.xcodeproj/xcshareddata/xcschemes/UnrarKit.xcscheme
> +   LastUpgradeVersion = "1400"
- [ ] Please revert

2022-08-01 20:53 UTC, gpotari commented
Forgot to mention that I was building with latest Xcode beta 4. And it actually didn't compile, gave me the mentioned error. 
Thank you for your review, going to fix them soon.

2022-08-02 00:33 UTC, abbeycode commented
Ok, that makes more sense. Feel free to and everything to “doesn’t compile with Xcode 14”

2022-08-02 09:10 UTC, gpotari commented
Modified

2026-02-19 13:53 UTC, closed without merging